{{- if .Values.ingress.enabled -}}
{{- $fullName := include "selfservice-portal.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfservice-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints: []
  routes:
  {{- if .Values.ingress.routes -}}
  {{- with .Values.ingress.routes }}
    {{- toYaml . | nindent 4}}

  {{- end }}

  {{ else }}
    - kind: Rule
      match: {{ .Values.ingress.match }}
      {{- with .Values.ingress.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- if .Values.ingress.services -}}
      {{- with .Values.ingress.services }}
      services:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{ else }}
      services:
        - kind: Service
          name: {{ include "selfservice-portal.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: http
      {{- end }}
  {{- end }}

{{- end }}
