{{- if .Values.ingress.prefixMiddleware.enabled -}}
{{- $fullName := include "selfservice-portal.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfservice-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.prefixMiddleware.prefix }}
{{- end }}
