apiVersion: v1
kind: Service
metadata:
  name: {{ include "selfservice-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selfservice-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: http
  selector:
    {{- include "selfservice-portal.selectorLabels" . | nindent 4 }}
