/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgNewRelease = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      d="M22.884 12.592a.2.2 0 000-.264l-2.267-2.583a.2.2 0 01-.05-.15l.317-3.42a.2.2 0 00-.155-.214L17.374 5.2a.2.2 0 01-.128-.093L15.49 2.151a.2.2 0 00-.251-.082l-3.16 1.357a.2.2 0 01-.158 0L8.761 2.07a.2.2 0 00-.25.082L6.753 5.106a.2.2 0 01-.128.093l-3.354.753a.2.2 0 00-.156.213l.316 3.42a.2.2 0 01-.048.15l-2.269 2.593a.2.2 0 000 .264l2.268 2.583a.2.2 0 01.05.15l-.317 3.43a.2.2 0 00.155.214l3.355.762a.2.2 0 01.128.093l1.756 2.955a.2.2 0 00.251.081l3.16-1.366a.2.2 0 01.158 0l3.16 1.357a.2.2 0 00.25-.082l1.757-2.955a.2.2 0 01.128-.093l3.355-.762a.2.2 0 00.155-.214l-.316-3.42a.2.2 0 01.049-.15l2.267-2.583zM13 17.26a.2.2 0 01-.2.2h-1.6a.2.2 0 01-.2-.2v-1.6c0-.11.09-.2.2-.2h1.6c.11 0 .2.09.2.2v1.6zm0-4a.2.2 0 01-.2.2h-1.6a.2.2 0 01-.2-.2v-5.6c0-.11.09-.2.2-.2h1.6c.11 0 .2.09.2.2v5.6z"
      fill="currentColor"
    />
  </svg>
))
export default SvgNewRelease
