apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfservice-portal
  namespace: selfservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfservice-portal
  template:
    metadata:
      labels:
        app: selfservice-portal
    spec:
      containers:
        - name: app
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice-portal:{{BUILD_NUMBER}}
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
