apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: selfservice-portal
  namespace: selfservice
spec:
  entryPoints: []
  routes:
    - kind: Rule
      match: Host(`build.dfds.cloud`)
      priority: 100
      middlewares: []
      services:
        - kind: Service
          name: selfservice-portal
          namespace: selfservice
          port: external
