/* eslint-disable no-console */
const path = require('path')
const util = require('util')
const rimraf = require('rimraf')
const chalk = require('chalk')
const fse = require('fs-extra')
const humps = require('humps')
const prettier = require('prettier')

const cjsPath = path.resolve(__dirname, '../dist/cjs')

// In order to generate the sass file we need the cjs build to be in place. Here we check if the cjs build exists.
if (!fse.pathExistsSync(cjsPath)) {
  console.log(chalk.red(`cjs folder does not exist. Please run build before generate-sass`))
  process.exit()
}

const colorPalette = require(cjsPath).colorPalette
const outPath = path.resolve(__dirname, '../dist/css')

const EOL = '\r\n'

const rimrafp = util.promisify(rimraf)
const kebabCase = string => humps.decamelize(string, { separator: '-' })

/**
 * Generates a sass file with color variables definitions
 */
async function generate(fileName) {
  await rimrafp(outPath)

  const outFile = path.resolve(outPath, fileName)

  console.log(chalk.green(`Generating ${outFile}`))

  const lines = []
  lines.push('/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */')
  lines.push(':root {')
  lines.push(...generateLines(colorPalette))
  lines.push('}')

  const content = await prettierFormat(lines.join(EOL))
  await fse.outputFile(outFile, content, 'utf8')
}

/**
 * Generates an array of color names and their values for each entry in palette
 * eg.: --color-background-grey: #eef0f1;
 */
function generateLines(palette) {
  return Object.entries(palette).reduce((lines, [paletteName, colors]) => {
    lines.push(`/* ${paletteName} */`)
    const colorLines = Object.entries(colors).map(([colorName, colorValue]) => {
      const rgb = hexToRGBComponents(colorValue)
      return `--color-${kebabCase(colorName)}: ${colorValue || 'inherit'};
      --color-${kebabCase(colorName)}-rgb: ${`${rgb.r}, ${rgb.g}, ${rgb.b}`};
      `
    })

    lines.push(...colorLines)
    return lines
  }, [])
}

function hexToRGBComponents(hexColor) {
  const hex = hexColor.replace('#', '')

  return {
    r: parseInt(hex.substring(0, 2), 16),
    g: parseInt(hex.substring(2, 4), 16),
    b: parseInt(hex.substring(4, 6), 16),
  }
}

/**
 * Format using Prettier
 */
async function prettierFormat(string) {
  const prettierConfig = await prettier.resolveConfig(process.cwd())
  return prettier.format(string, { parser: 'css', ...prettierConfig })
}

if (require.main === module) {
  generate('colors.css', false).catch(ex => {
    console.log(chalk.red('Failed to generate file colors.css'))
    console.log(ex)
  })
}

module.export = generate
