module.exports = [
  {
    languageOptions: {
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        process: "readonly",
        module: "readonly",
        require: "readonly",
        __dirname: "readonly",
        exports: "readonly",
        global: "readonly",
        Buffer: "readonly",
        Symbol: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
        Int8Array: "readonly",
        Uint8Array: "readonly",
        Uint8ClampedArray: "readonly",
        Int16Array: "readonly",
        Uint16Array: "readonly",
        Int32Array: "readonly",
        Uint32Array: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
        Reflect: "readonly",
        Proxy: "readonly",
        Intl: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        EvalError: "readonly",
        RangeError: "readonly",
        ReferenceError: "readonly",
        SyntaxError: "readonly",
        TypeError: "readonly",
        URIError: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        parseFloat: "readonly",
        parseInt: "readonly",
        decodeURI: "readonly",
        decodeURIComponent: "readonly",
        encodeURI: "readonly",
        encodeURIComponent: "readonly",
        escape: "readonly",
        unescape: "readonly",
        btoa: "readonly",
        atob: "readonly",
        fetch: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        BigInt: "readonly",
        globalThis: "readonly",
      },
    },
    plugins: {
      react: require("eslint-plugin-react"),
      "@typescript-eslint": require("@typescript-eslint/eslint-plugin"),
      prettier: require("eslint-plugin-prettier"),
    },
    rules: {
      "prettier/prettier": "error",
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    ignores: ["dist/", "build/", "node_modules/"],
  },
];
