name: Test

on:
  push:
    branches:
      - 'develop'
      - 'chore/dev-env-pipeline'
    paths:
      - '.github/workflows/shared-env-develop.yml'
      - 'src/**'
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        default: false
        required: false
        type: boolean
        description: "Trigger build"
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency:
  group: 'selfservice-portal_test'
  cancel-in-progress: true

jobs:
  deploy:
    name:  '01 - Linux'
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
        arch: ['x86_64']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'src'
      - uses: actions/checkout@v3
        with:
          repository: 'dfds/selfservice-setup'
          path: 'selfservice-setup'
          token: ${{ secrets.SSU_APPS_GH_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build and run necessary services for testing
        shell: bash
        run: |
          cd selfservice-setup
          disablegitssh=true ./init.sh
          docker-compose up -d
      # - uses: ./ssu-apps/.github/actions/build_push_container_ecr
      #   name: Build & push container
      #   id: build_push_container
      #   with:
      #     context_path: ./src
      #     tag: develop
      #     repo: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice-portal
      #     role_arn: ${{ secrets.SSU_APPS_GH_IAM_ROLE }}
      #     aws_region: eu-central-1
      #     sha_tag_prefix: develop
      #     args: |
      #       REACT_APP_API_BASE_URL=https://internal.hellman.oxygen.dfds.cloud/ssu/dev-env/develop/api
      #       REACT_APP_AUTH_REDIRECT_URL=https://internal.hellman.oxygen.dfds.cloud/ssu/dev-env/develop
      #       REACT_APP_PUBLIC_URL=https://internal.hellman.oxygen.dfds.cloud/ssu/dev-env/develop
      #       PUBLIC_URL=/ssu/dev-env/develop
      # - shell: bash
      #   name: "Update image tag"
      #   env:
      #     IMAGE_TAG: develop-${{ steps.build_push_container.outputs.sha }}
      #   run: |
      #     wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /tmp/yq
      #     chmod +x /tmp/yq
      #     cd ssu-apps/apps/ssu
      #     /tmp/yq -i '.spec.values.image.tag = strenv(IMAGE_TAG)' selfservice-portal.yaml
      #     git pull
      #     git config user.name "ssu-apps SA"
      #     git config user.email ssu-apps@dfds.cloud
      #     git add selfservice-portal.yaml
      #     git commit -m "Updated selfservice-portal image tag to develop-${{ steps.build_push_container.outputs.sha }}"
      #     git push